version: '3.5'

services:
  loadbalancer:
    image: haproxy:lts-alpine
    container_name: haproxy
    restart: always
    ports:
      - 8080:8080
      # - 8404:8404
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro



