version: '3.5'

services:
  database:
    image: mariadb:10.4.8   # mariadb:10.5.3-bionic
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      - internal-network
    labels:
      - "traefik.enable=false"
  symfony:
    build:
      context: ./php-fpm
      cache_from:
        - php:fpm-alpine
    image: symfony-php:fpm-alpine 
    depends_on:
      - ${SRV_DB}
        #  user: 1000:1000
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./apps/my-symfony-app:/var/www
    depends_on: 
      - ${SRV_DB}
    links:
      - ${SRV_DB}
    networks: 
      - outside-network
      - internal-network
  web001:
    image: nginx:stable-alpine
    volumes:
      - ./apps/my-symfony-app/public:/var/www/public
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ${SRV_APP}
    labels:
      - "traefik.backend=${SRV_WEB}"
      - "traefik.frontend.rule=Host:dev.symfony.${DOMAIN}"
      - "traefik.docker.network=outside-network"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=https"
    networks:
      - outside-network
      - internal-network
volumes: 
  apps:
  db-data:
networks:
  internal-network:
    external: false
  outside-network:
    external: true
