version: '3.5'

services:
  squid:
     build:
      context: ./dockerfile
      cache_from:
        - alpine:edge
     image: squid-4.11:edge
     hostname: cubsna001
     container_name: squid
     ports:
      - "3128:3128"
     volumes:
      - ./squid/cache:/var/spool/squid
      - ./etc/squid.conf:/etc/squid/squid.conf:ro
      - ./squid/log:/var/log/squid:rw
     restart: always
volumes: 
    squid:
