version: '3.1'
services:

  web:
    image: ansible/awx:17.0.1
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: ${user}
    restart: unless-stopped
    volumes:
      - ./data/supervisor-socket:/var/run/supervisor
      - ./data/rsyslog-socket:/var/run/awx-rsyslog/
      - ./data/rsyslog-config:/var/lib/awx/rsyslog/
      - ./etc/SECRET_KEY:/etc/tower/SECRET_KEY
      - ./etc/environment.sh:/etc/tower/conf.d/environment.sh
      - ./etc/credentials.py:/etc/tower/conf.d/credentials.py
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/redis_socket:/var/run/redis/:rw
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx:17.0.1
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    user: ${user}
    restart: unless-stopped
    volumes:
      - ./data/supervisor-socket:/var/run/supervisor
      - ./data/rsyslog-socket:/var/run/awx-rsyslog/
      - ./data/rsyslog-config:/var/lib/awx/rsyslog/
      - ./etc/SECRET_KEY:/etc/tower/SECRET_KEY
      - ./etc/environment.sh:/etc/tower/conf.d/environment.sh
      - ./etc/credentials.py:/etc/tower/conf.d/credentials.py
      - ./data/redis_socket:/var/run/redis/:rw
    environment:
      AWX_SKIP_MIGRATIONS: "1"
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./data/redis_socket:/var/run/redis/:rw

  postgres:
    image: postgres:12.4-alpine
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - ./db-data/:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      http_proxy: 
      https_proxy: 
      no_proxy: 


volumes:
  data: