version: '3.5'

services:
  vpnclient:
    build: 
      context: ./dockerfile_openvpn
      cache_from:
        - alpine:latest
    image: openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports: 
      - '3128:3128'
    volumes:
      - /dev/net:/dev/net:z
      - ./openvpn/client.ovpn:/vpn/client.ovpn
    # command: 'server;user;password[;port]'
  squid:
    build: 
      context: ./dockerfile_squid
      cache_from:
        - alpine:latest
    image: squid
    volumes:
      - ./squid/cache:/var/cache/squid
      - ./etc/squid.conf:/etc/squid/squid.conf:ro
      - ./squid/log:/var/log/squid:rw
      - /etc/localtime:/etc/localtime:ro
    shm_size: 1G
    restart: always  
    depends_on:
      - vpnclient
    network_mode: "service:vpnclient"
    stdin_open: true
    tty: true
networks:
  default:
