version: '3.1'

services:
  mirrorclamav:
    build:
      context: ./dockerfile
    image: clamav:mirror-v1
    volumes:
      - ./data:/html/database 
    restart: always
    networks: 
      - outside-network
    labels: 
      - "traefik.backend=mirrorclamav"
      - "traefik.frontend.rule=Host:mirror-clamav.unixfree.org"
      - "traefik.docker.network=outside-network"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=https"  
    environment:
      - VIRTUAL_HOST
volumes:
  data:
networks: 
  outside-network:
    external: true
    