version: '3.1'

services:
  mirrorclamav:
    build:
      context: ./dockerfile
    image: clamav:mirror-v1
    volumes:
      - ./data:/html/database 
    restart: always
    networks: 
      - outside-network
    labels: 
      - "traefik.backend=mirrorclamav"
      - "traefik.frontend.rule=Host:mirror-clamav.unixfree.org"
      - "traefik.docker.network=outside-network"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=https"  
    environment:
      - VIRTUAL_HOST
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
  cvdupdate:
    build:
      context: ./dockerfile_cvdupdate
    image: cvdclamav:v1
    volumes:
      - ./data:/data
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
volumes:
  data:
networks: 
  outside-network:
    external: true
    
