version: '3.1'

services:
  mirrorclamav:
    build:
      context: ./dockerfile
    image: clamav:mirror-v1
    ports:
      - 80:80
    volumes:
      - ./data:/html/database 
    restart: always
    environment:
      - VIRTUAL_HOST
volumes:
  data: