version: '3.5'

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - outside-network
  joomla:
    image: joomla:php7.4-fpm-alpine
    restart: always
    depends_on: 
      - joomladb
    links:
      - joomladb
    environment:
      - JOOMLA_DB_HOST=joomladb:3306
      - JOOMLA_DB_USER=root
      - JOOMLA_DB_PASSWORD=secretpassword
      - JOOMLA_DB_NAME=db
    volumes:
    - ./html:/var/www/html
    networks: 
      - outside-network
      - internal-network
  joomladb:
    image: mariadb:10.4.8
    restart: always
    networks:
      - internal-network
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=secretpassword
    volumes:
      - ./db_data:/var/lib/mysql
volumes: 
  html:
  db-data:
networks:
  internal-network:
    external: false
  outside-network:
    external: true
