version: '3.4'

services:
  vpnclient:
    build: 
      context: ./openvpn-client
      cache_from:
        - alpine:latest
    image: openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./openvpn/client.ovpn:/vpn/client.ovpn
networks:
  default: